### ISSUE TITLE
JEI weirdness

### ISSUE THREAD

**Issue by Voxel-Friend** [mallrat208/Expanded-Arcanum#2]
![2018-08-27_21 35 07](https://user-images.githubusercontent.com/12395262/44854281-bda4cc80-ac2d-11e8-920e-8c85aa9ba9a7.png)
Should be self explanatory what the issue is. Any clue as to the cause?

**Comment by mallrat208** [comment]
So funny story. I originally made that recipe using the ore tag blockVoid and it showed the item as the missing texture item. 

I then manually registered the block and it started showing the actual image itself.

I'm fairly certain the actual fault is with Thaumcraft

**Comment by wamc2017** [comment]
Yeah, that's a bug in Thaumcrafts Api, it registers blockVoid with the wrong metadata:

https://github.com/Azanor/thaumcraft-api/issues/45

**Comment by Voxel-Friend** [comment]
Welp, now that this is verified to be on azanor's end, gonna close this. Cheers!
